### ISSUE TITLE
Bom dia JH

### ISSUE THREAD

**Issue by joaqu1m** [JHoliveira23/Criando-meu-primeiro-site#1]
Não achei onde posso criar uma conta

**Comment by JHoliveira23** [comment]
Obrigado por sua sugestão e por colaborar para que o site seja melhor!
Para mais problemas que tenha encontrado neste repositório basta trazer mais relatórios de problemas ocorridos.

Muito obrigado pela sua colaboração!

![unnamed(8)](https://user-images.githubusercontent.com/105952517/170352101-e385ccc7-9b13-4816-bd0c-328606dbe212.jpg)


Conheça mais meus projetos:
* Meus projetos grátis no [GitHub](url)
* [Intagram](url)
* Meu canal no [YouTube](url)
